'use client';
import { useEffect, useState } from 'react';
import { NirmaanHeader } from '../components/NirmaanHeader';
import { CheckCircle2, Clock, ImageIcon, Volume2 } from 'lucide-react';

type Evidence = { id: string; kind: 'image' | 'audio'; capturedAt: string; dataUrl: string; mimeType: string };
type Event = { clientEventId: string; discipline: string; rawText: string; eventTimestampHw: string; monotonicSeq: number; status: 'PENDING_LOCAL' | 'SYNCED'; evidence: Evidence[] };
const display = (value: string) => new Date(value).toLocaleString(undefined, { dateStyle: 'full', timeStyle: 'medium' });

export function EvidenceTimelinePage() {
  const [items, setItems] = useState<Event[]>([]);
  useEffect(() => { try { setItems(JSON.parse(localStorage.getItem('nirmaan_field_outbox') || '[]')); } catch { setItems([]); } }, []);
  const ordered = [...items].sort((a, b) => new Date(b.eventTimestampHw).getTime() - new Date(a.eventTimestampHw).getTime());
  return <div className="min-h-screen bg-background"><NirmaanHeader currentTab="evidence" /><main className="max-w-6xl mx-auto px-4 sm:px-6 py-8 space-y-6"><div><h2 className="text-2xl font-bold tracking-tight">Admin evidence timeline</h2><p className="text-xs text-muted-foreground mt-1">Photos and voice notes ordered by on-device capture timestamp. Upload time never changes evidence order.</p></div><div className="rounded-2xl border border-border bg-card overflow-hidden">{ordered.length ? ordered.map((item) => <article key={item.clientEventId} className="p-5 border-b border-border last:border-0 grid md:grid-cols-[180px_1fr] gap-5"><div className="font-mono text-xs"><div className="flex gap-2 items-center font-bold text-primary"><Clock className="w-4 h-4" /> Seq #{item.monotonicSeq}</div><p className="text-muted-foreground mt-2 leading-relaxed">{display(item.eventTimestampHw)}</p><p className="mt-2 inline-flex text-[10px] font-bold rounded-full px-2 py-1 bg-muted">{item.discipline}</p></div><div><div className="flex items-start justify-between gap-4"><p className="text-sm font-semibold">{item.rawText}</p>{item.status === 'SYNCED' ? <span className="text-[10px] text-emerald-600 font-bold inline-flex gap-1 items-center"><CheckCircle2 className="w-3.5 h-3.5" /> SYNCED</span> : <span className="text-[10px] text-amber-600 font-bold">ON DEVICE</span>}</div><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4">{item.evidence.map((evidence) => <div className="rounded-xl border border-border overflow-hidden" key={evidence.id}>{evidence.kind === 'image' ? <img src={evidence.dataUrl} alt="Field evidence" className="w-full aspect-video object-cover" /> : <div className="aspect-video bg-primary/5 text-primary flex items-center justify-center"><Volume2 /></div>}<div className="p-2 text-[10px] font-medium flex gap-1 items-center">{evidence.kind === 'image' ? <ImageIcon className="w-3 h-3" /> : <Volume2 className="w-3 h-3" />}{new Date(evidence.capturedAt).toLocaleTimeString()}</div>{evidence.kind === 'audio' && <audio controls className="w-full h-8 px-1 pb-1" src={evidence.dataUrl} />}</div>)}</div></div></article>) : <div className="py-16 text-center text-sm text-muted-foreground">No field evidence has reached this device yet. Capture an item in Field Logger to review it here.</div>}</div></main></div>;
}
