'use client';
import React, { useEffect, useRef, useState } from 'react';
import { NirmaanHeader } from '../components/NirmaanHeader';
import { syncFieldEventsBatch } from '../operationsClient';
import { Bell, Camera, CheckCircle2, Clock, Download, Mic, MicOff, Radio, RefreshCw, Send, Volume2, Wifi, WifiOff } from 'lucide-react';

type EvidenceKind = 'image' | 'audio';
interface Evidence { id: string; kind: EvidenceKind; name: string; capturedAt: string; dataUrl: string; mimeType: string; }
interface LocalOutboxEvent { clientEventId: string; deviceId: string; sourceType: 'MOBILE_VOICE' | 'MOBILE_FORM' | 'EXCEL_DPR'; discipline: string; rawText: string; quantityMeters: number; eventTimestampHw: string; monotonicSeq: number; status: 'PENDING_LOCAL' | 'SYNCED'; evidence: Evidence[]; }
const OUTBOX = 'nirmaan_field_outbox'; const DEVICE = 'OIL-FIELD-RUGGED-09'; const sample = 'Completed 120m trenching near Duliajan Valve Station. Dense rocky soil encountered.';
const fileToDataUrl = (file: Blob) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
const stamp = (value: string) => new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'medium' });

export function FieldLogPage() {
  const [offline, setOffline] = useState(false); const [note, setNote] = useState(''); const [discipline, setDiscipline] = useState('Piping'); const [quantity, setQuantity] = useState(25); const [recording, setRecording] = useState(false); const [seconds, setSeconds] = useState(0); const [evidence, setEvidence] = useState<Evidence[]>([]); const [outbox, setOutbox] = useState<LocalOutboxEvent[]>([]); const [installPrompt, setInstallPrompt] = useState<any>(null); const [feedback, setFeedback] = useState<string | null>(null);
  const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]); const imageInput = useRef<HTMLInputElement>(null);
  useEffect(() => { try { setOutbox(JSON.parse(localStorage.getItem(OUTBOX) || '[]')); } catch { setOutbox([]); } }, []);
  useEffect(() => { localStorage.setItem(OUTBOX, JSON.stringify(outbox)); }, [outbox]);
  useEffect(() => { if (!recording) return; const id = window.setInterval(() => setSeconds((s) => s + 1), 1000); return () => clearInterval(id); }, [recording]);
  useEffect(() => { const onInstall = (event: Event) => { event.preventDefault(); setInstallPrompt(event); }; window.addEventListener('beforeinstallprompt', onInstall); return () => window.removeEventListener('beforeinstallprompt', onInstall); }, []);
  useEffect(() => { const online = () => { setOffline(false); setFeedback('Connection restored — your queued evidence is ready to sync.'); }; window.addEventListener('online', online); return () => window.removeEventListener('online', online); }, []);
  const captureImage = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const capturedAt = new Date().toISOString(); const dataUrl = await fileToDataUrl(file); setEvidence((items) => [...items, { id: crypto.randomUUID(), kind: 'image', name: file.name || 'site-photo.jpg', capturedAt, dataUrl, mimeType: file.type }]); event.target.value = ''; };
  const toggleRecord = async () => { if (recording && recorder.current) { recorder.current.stop(); setRecording(false); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const mediaRecorder = new MediaRecorder(stream); chunks.current = []; mediaRecorder.ondataavailable = (event) => chunks.current.push(event.data); mediaRecorder.onstop = async () => { const blob = new Blob(chunks.current, { type: mediaRecorder.mimeType || 'audio/webm' }); const capturedAt = new Date().toISOString(); const dataUrl = await fileToDataUrl(blob); setEvidence((items) => [...items, { id: crypto.randomUUID(), kind: 'audio', name: `voice-note-${capturedAt.slice(11, 19).replaceAll(':', '')}.webm`, capturedAt, dataUrl, mimeType: blob.type }]); stream.getTracks().forEach((track) => track.stop()); setNote((text) => text || sample); }; recorder.current = mediaRecorder; mediaRecorder.start(); setSeconds(0); setRecording(true); } catch { setFeedback('Microphone permission is needed to capture a voice note.'); } };
  const queue = () => { if (!note.trim() && evidence.length === 0) { setFeedback('Add an observation, photo, or voice note before saving offline.'); return; } const next = Math.max(1043, ...outbox.map((item) => item.monotonicSeq)) + 1; const timestamp = new Date().toISOString(); setOutbox((items) => [{ clientEventId: crypto.randomUUID(), deviceId: DEVICE, sourceType: evidence.some((item) => item.kind === 'audio') ? 'MOBILE_VOICE' : 'MOBILE_FORM', discipline, rawText: note || 'Evidence captured without written note.', quantityMeters: quantity, eventTimestampHw: timestamp, monotonicSeq: next, status: 'PENDING_LOCAL', evidence }, ...items]); setNote(''); setEvidence([]); setFeedback('Saved on this device with a tamper-evident capture timestamp.'); };
  const sync = async () => { const pending = outbox.filter((item) => item.status === 'PENDING_LOCAL'); if (!pending.length) return; if (offline || !navigator.onLine) { setFeedback('You are offline. Evidence remains in the local outbox until a connection is available.'); return; } await syncFieldEventsBatch({ projectId: 'proj-oil-assam-01', events: pending.map(({ clientEventId, deviceId, sourceType, rawText, eventTimestampHw, monotonicSeq }) => ({ clientEventId, deviceId, sourceType, rawText, eventTimestampHw, monotonicSeq, supervisorId: 'user-field-supervisor' })) }); setOutbox((items) => items.map((item) => ({ ...item, status: 'SYNCED' }))); setFeedback(`${pending.length} timestamped record${pending.length === 1 ? '' : 's'} synced to the planner timeline.`); };
  const install = async () => { if (!installPrompt) return; await installPrompt.prompt(); setInstallPrompt(null); }; const pending = outbox.filter((item) => item.status === 'PENDING_LOCAL').length;
  const enableNotifications = async () => { if (!('Notification' in window)) { setFeedback('Notifications are not available in this browser.'); return; } const permission = await Notification.requestPermission(); setFeedback(permission === 'granted' ? 'Notifications enabled — Nirmaan Setu will alert you when evidence is ready to sync.' : 'Notifications were not enabled.'); };
  return <div className="min-h-screen bg-background pb-12"><NirmaanHeader currentTab="field-log" /><main className="max-w-4xl mx-auto px-4 sm:px-6 py-6 space-y-6">
    <section className="rounded-2xl border border-border bg-card p-4 flex flex-col sm:flex-row justify-between gap-4 shadow-sm"><div className="flex gap-3"><div className={`p-2 rounded-xl ${offline ? 'bg-amber-500/10 text-amber-600' : 'bg-emerald-500/10 text-emerald-600'}`}>{offline ? <WifiOff /> : <Wifi />}</div><div><p className="text-sm font-bold">{offline ? 'Offline capture is active' : 'Secure sync connection active'}</p><p className="text-xs text-muted-foreground">Every file is stamped at capture and held locally until it can be reconciled.</p></div></div><div className="flex flex-wrap gap-2"><button onClick={() => setOffline(!offline)} className="px-3 py-2 rounded-lg border border-border text-xs font-semibold">{offline ? 'Go online' : 'Test offline mode'}</button><button onClick={enableNotifications} className="px-3 py-2 rounded-lg border border-border text-xs font-semibold inline-flex gap-1.5 items-center"><Bell className="w-3.5 h-3.5" /> Alerts</button>{installPrompt && <button onClick={install} className="px-3 py-2 rounded-lg bg-primary text-primary-foreground text-xs font-bold inline-flex gap-1.5 items-center"><Download className="w-4 h-4" /> Install app</button>}</div></section>
    {feedback && <div className="p-3 rounded-xl border border-primary/20 bg-primary/5 text-xs font-semibold flex justify-between"><span>{feedback}</span><button onClick={() => setFeedback(null)}>×</button></div>}
    <section className="rounded-3xl border border-border bg-card p-6 shadow-lg space-y-6"><div className="flex justify-between border-b border-border pb-4"><div><h2 className="font-bold flex gap-2 items-center"><Radio className="w-5 h-5 text-primary" /> Field evidence capture</h2><p className="text-xs text-muted-foreground mt-1">Works without signal — syncs when the device reconnects.</p></div><span className="text-[10px] font-mono rounded bg-muted px-2 py-1 h-fit">{DEVICE}</span></div><div className="grid grid-cols-2 gap-3"><button onClick={() => imageInput.current?.click()} className="min-h-28 rounded-2xl border-2 border-dashed border-border hover:border-primary bg-muted/20 flex flex-col items-center justify-center gap-2 text-sm font-bold"><Camera className="w-7 h-7 text-primary" /> Capture photo</button><button onClick={toggleRecord} className={`min-h-28 rounded-2xl border flex flex-col items-center justify-center gap-2 text-sm font-bold ${recording ? 'bg-red-600 text-white border-red-600 animate-pulse' : 'bg-primary text-primary-foreground'}`}>{recording ? <MicOff className="w-7 h-7" /> : <Mic className="w-7 h-7" />}{recording ? `Stop recording · ${seconds}s` : 'Record voice note'}</button><input ref={imageInput} onChange={captureImage} className="hidden" type="file" accept="image/*" capture="environment" /></div>
      {evidence.length > 0 && <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{evidence.map((item) => <div key={item.id} className="border border-border rounded-xl overflow-hidden bg-muted/20"><div className="aspect-square bg-muted flex items-center justify-center">{item.kind === 'image' ? <img src={item.dataUrl} alt="Captured site evidence" className="w-full h-full object-cover" /> : <Volume2 className="text-primary" />}</div><div className="p-2 text-[10px]"><p className="font-bold truncate">{item.kind === 'image' ? 'Site photo' : 'Voice note'}</p><p className="text-muted-foreground">{stamp(item.capturedAt)}</p></div></div>)}</div>}
      <div className="grid sm:grid-cols-2 gap-4"><label className="text-xs font-bold">Discipline<select value={discipline} onChange={(event) => setDiscipline(event.target.value)} className="mt-1.5 w-full p-3 rounded-xl border border-border bg-background">{['Piping','Civil','Electrical','Instrumentation'].map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs font-bold">Measured quantity<input value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} type="number" className="mt-1.5 w-full p-3 rounded-xl border border-border bg-background" /></label></div><label className="block text-xs font-bold">Observation / transcript<textarea value={note} onChange={(event) => setNote(event.target.value)} rows={3} placeholder="Describe progress, conditions, incident, or potential failure." className="mt-1.5 w-full p-3 rounded-xl border border-border bg-background text-sm font-normal" /></label><button onClick={queue} className="w-full p-3 rounded-xl bg-primary text-primary-foreground text-sm font-bold inline-flex justify-center items-center gap-2"><Send className="w-4 h-4" /> Save to offline outbox</button></section>
    <section className="rounded-3xl border border-border bg-card p-6 space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-bold text-sm">Local outbox · chronological evidence</h3><p className="text-xs text-muted-foreground">Ordered by hardware capture timestamp, not upload time.</p></div><button onClick={sync} disabled={!pending} className="px-4 py-2 rounded-lg bg-primary text-primary-foreground text-xs font-bold disabled:opacity-50 inline-flex gap-2 items-center"><RefreshCw className="w-3.5 h-3.5" /> Sync {pending || ''}</button></div><div className="divide-y divide-border">{outbox.length ? [...outbox].sort((a,b) => new Date(b.eventTimestampHw).getTime() - new Date(a.eventTimestampHw).getTime()).map((item) => <div key={item.clientEventId} className="py-3 flex gap-3"><div className="pt-0.5">{item.status === 'SYNCED' ? <CheckCircle2 className="w-4 h-4 text-emerald-600" /> : <Clock className="w-4 h-4 text-amber-600" />}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold">{item.rawText}</p><p className="text-[11px] text-muted-foreground mt-1">{stamp(item.eventTimestampHw)} · Seq #{item.monotonicSeq} · {item.evidence.length} attachment{item.evidence.length === 1 ? '' : 's'}</p></div><span className="text-[10px] font-bold">{item.status === 'SYNCED' ? 'SYNCED' : 'QUEUED'}</span></div>) : <p className="py-6 text-center text-xs text-muted-foreground">Your offline evidence will appear here.</p>}</div></section>
  </main></div>;
}
