'use client';

import React, { useEffect, useRef, useState } from 'react';
import { Bell, Camera, CheckCircle2, Clock, Download, MapPin, Mic, MicOff, Radio, RefreshCw, Send, Volume2, Wifi, WifiOff, X } from 'lucide-react';
import { NirmaanHeader } from '../components/NirmaanHeader';
import { syncFieldEventsBatch, useProjects } from '../operationsClient';

type EvidenceKind = 'image' | 'audio';
interface GeoTag { latitude: number; longitude: number; accuracyMeters: number; capturedAt: string; }
interface Evidence { id: string; kind: EvidenceKind; name: string; capturedAt: string; durationSeconds?: number; dataUrl: string; mimeType: string; geoTag?: GeoTag; }
interface LocalOutboxEvent { clientEventId: string; deviceId: string; sourceType: 'MOBILE_VOICE' | 'MOBILE_FORM' | 'EXCEL_DPR'; discipline: string; quantityMeters: number; rawText: string; eventTimestampHw: string; geoTag?: GeoTag; monotonicSeq: number; status: 'PENDING_LOCAL' | 'SYNCED'; evidence: Evidence[]; }
const OUTBOX = 'nirmaan_field_outbox';
const DEVICE = 'NIRMAAN-FIELD-DEVICE';
const fileToDataUrl = (file: Blob) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
const stamp = (value: string) => new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'medium' });
const getCurrentPosition = () => new Promise<GeoTag>((resolve, reject) => {
  if (!navigator.geolocation) { reject(new Error('GPS is not available in this browser.')); return; }
  navigator.geolocation.getCurrentPosition(
    (position) => resolve({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracyMeters: position.coords.accuracy, capturedAt: new Date(position.timestamp).toISOString() }),
    (error) => reject(new Error(error.code === error.PERMISSION_DENIED ? 'Location permission was denied.' : 'Unable to determine your current location.')),
    { enableHighAccuracy: true, timeout: 15000, maximumAge: 60000 },
  );
});

export function FieldLogPage() {
  const { projects, isLoading: isLoadingProjects, error: projectsError } = useProjects();
  const [selectedProjectId, setSelectedProjectId] = useState(''); const [offline, setOffline] = useState(false); const [note, setNote] = useState(''); const [discipline, setDiscipline] = useState('Piping'); const [quantity, setQuantity] = useState(25); const [recording, setRecording] = useState(false); const [seconds, setSeconds] = useState(0); const [evidence, setEvidence] = useState<Evidence[]>([]); const [outbox, setOutbox] = useState<LocalOutboxEvent[]>([]); const [installPrompt, setInstallPrompt] = useState<any>(null); const [feedback, setFeedback] = useState<string | null>(null); const [isTranscribing, setIsTranscribing] = useState(false); const [requirePhoto, setRequirePhoto] = useState(false); const [requireGpsTag, setRequireGpsTag] = useState(false); const [isLocating, setIsLocating] = useState(false); const [isSubmitting, setIsSubmitting] = useState(false);
  const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]); const imageInput = useRef<HTMLInputElement>(null); const pendingPhotoGeoTag = useRef<GeoTag | undefined>(undefined); const recordingStartedAt = useRef<{ iso: string; milliseconds: number } | null>(null);
  useEffect(() => { try { setOutbox(JSON.parse(localStorage.getItem(OUTBOX) || '[]')); } catch { setOutbox([]); } }, []);
  useEffect(() => { if (!selectedProjectId && projects[0]) setSelectedProjectId(projects[0].id); }, [projects, selectedProjectId]);
  useEffect(() => { localStorage.setItem(OUTBOX, JSON.stringify(outbox)); }, [outbox]);
  useEffect(() => { if (!recording) return; const updateElapsedTime = () => setSeconds(Math.floor((Date.now() - (recordingStartedAt.current?.milliseconds || Date.now())) / 1000)); updateElapsedTime(); const id = window.setInterval(updateElapsedTime, 250); return () => clearInterval(id); }, [recording]);
  useEffect(() => { const onInstall = (event: Event) => { event.preventDefault(); setInstallPrompt(event); }; window.addEventListener('beforeinstallprompt', onInstall); return () => window.removeEventListener('beforeinstallprompt', onInstall); }, []);
  useEffect(() => { const online = () => { setOffline(false); setFeedback('Connection restored. Use Sync queued logs to send anything saved while offline.'); }; window.addEventListener('online', online); return () => window.removeEventListener('online', online); }, []);
  const startPhotoCapture = async () => { pendingPhotoGeoTag.current = undefined; if (requireGpsTag) { setIsLocating(true); try { pendingPhotoGeoTag.current = await getCurrentPosition(); } catch (cause) { setFeedback(cause instanceof Error ? `${cause.message} Turn off GPS required to attach this photo without a location tag.` : 'A GPS-tagged photo is required before saving.'); return; } finally { setIsLocating(false); } } imageInput.current?.click(); };
  const captureImage = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const capturedAt = new Date().toISOString(); try { const dataUrl = await fileToDataUrl(file); setEvidence((items) => [...items, { id: crypto.randomUUID(), kind: 'image', name: file.name || 'site-photo.jpg', capturedAt, dataUrl, mimeType: file.type || 'image/jpeg', geoTag: pendingPhotoGeoTag.current }]); setFeedback(pendingPhotoGeoTag.current ? 'Photo captured with its current GPS tag.' : 'Photo attached.'); } catch { setFeedback('The selected image could not be read. Please try again.'); } finally { pendingPhotoGeoTag.current = undefined; event.target.value = ''; } };
  const removeEvidence = (id: string) => setEvidence((items) => items.filter((item) => item.id !== id));
  const transcribeAudio = async (blob: Blob) => { setIsTranscribing(true); try { const body = new FormData(); body.append('audio', new File([blob], 'field-note.webm', { type: blob.type || 'audio/webm' })); const response = await fetch('/api/transcribe', { method: 'POST', body }); const result = await response.json() as { text?: string; error?: string }; if (!response.ok || !result.text) throw new Error(result.error); setNote(result.text); setFeedback('Voice note transcribed. Review the text, then save it.'); } catch (cause) { setFeedback(cause instanceof Error && cause.message ? cause.message : 'Voice note attached, but transcription was unavailable. Add the observation text manually.'); } finally { setIsTranscribing(false); } };
  const toggleRecord = async () => { if (recording && recorder.current) { recorder.current.stop(); setRecording(false); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const mediaRecorder = new MediaRecorder(stream); chunks.current = []; mediaRecorder.ondataavailable = (event) => chunks.current.push(event.data); mediaRecorder.onstop = async () => { const startedAt = recordingStartedAt.current || { iso: new Date().toISOString(), milliseconds: Date.now() }; const durationSeconds = Math.max(0, Math.round((Date.now() - startedAt.milliseconds) / 1000)); setSeconds(durationSeconds); const blob = new Blob(chunks.current, { type: mediaRecorder.mimeType || 'audio/webm' }); const dataUrl = await fileToDataUrl(blob); setEvidence((items) => [...items, { id: crypto.randomUUID(), kind: 'audio', name: `voice-note-${startedAt.iso.slice(11, 19).replaceAll(':', '')}.webm`, capturedAt: startedAt.iso, durationSeconds, dataUrl, mimeType: blob.type }]); recordingStartedAt.current = null; stream.getTracks().forEach((track) => track.stop()); await transcribeAudio(blob); }; recorder.current = mediaRecorder; recordingStartedAt.current = { iso: new Date().toISOString(), milliseconds: Date.now() }; mediaRecorder.start(); setSeconds(0); setRecording(true); } catch { setFeedback('Microphone permission is needed to capture a voice note.'); } };
  const syncItems = async (items: LocalOutboxEvent[]) => { if (!selectedProjectId) throw new Error('Select a project with an uploaded baseline before saving to the database.'); await syncFieldEventsBatch({ projectId: selectedProjectId, events: items.map(({ clientEventId, deviceId, sourceType, rawText, eventTimestampHw, geoTag, monotonicSeq, evidence }) => ({ clientEventId, deviceId, sourceType, rawText, eventTimestampHw, location: geoTag, monotonicSeq, audioRecordingUrl: evidence.find((item) => item.kind === 'audio')?.dataUrl })) }); };
  const saveLog = async () => { if (!note.trim()) { setFeedback(isTranscribing ? 'Wait for the voice note transcription to finish.' : 'Enter the progress observation before saving.'); return; } const photos = evidence.filter((item) => item.kind === 'image'); if (requirePhoto && photos.length === 0) { setFeedback('Attach at least one site photo, or turn off Photo required.'); return; } let geoTag: GeoTag | undefined; if (requireGpsTag) { try { setIsLocating(true); geoTag = await getCurrentPosition(); } catch (cause) { setFeedback(cause instanceof Error ? `${cause.message} Turn off GPS required to save without a location tag.` : 'A GPS-tagged log is required before saving.'); return; } finally { setIsLocating(false); } } const voiceCapturedAt = evidence.find((item) => item.kind === 'audio')?.capturedAt; const entry: LocalOutboxEvent = { clientEventId: crypto.randomUUID(), deviceId: DEVICE, sourceType: evidence.some((item) => item.kind === 'audio') ? 'MOBILE_VOICE' : 'MOBILE_FORM', discipline, quantityMeters: quantity, rawText: note.trim(), eventTimestampHw: voiceCapturedAt || geoTag?.capturedAt || new Date().toISOString(), geoTag, monotonicSeq: Math.max(1043, ...outbox.map((item) => item.monotonicSeq)) + 1, status: 'PENDING_LOCAL', evidence }; setOutbox((items) => [entry, ...items]); setNote(''); setEvidence([]); if (offline || !navigator.onLine) { setFeedback('Saved on this device. It will stay in the outbox until you are online and choose Sync.'); return; } setIsSubmitting(true); try { await syncItems([entry]); setOutbox((items) => items.map((item) => item.clientEventId === entry.clientEventId ? { ...item, status: 'SYNCED' } : item)); setFeedback('Saved to the database and sent to the reviewer queue.'); } catch (cause) { setFeedback(`${cause instanceof Error ? cause.message : 'Unable to save to the database.'} The log is safely queued for retry.`); } finally { setIsSubmitting(false); } };
  const sync = async () => { const pending = outbox.filter((item) => item.status === 'PENDING_LOCAL'); if (!pending.length) return; if (offline || !navigator.onLine) { setFeedback('You are offline. Evidence remains in the local outbox until a connection is available.'); return; } setIsSubmitting(true); try { await syncItems(pending); setOutbox((items) => items.map((item) => ({ ...item, status: 'SYNCED' }))); setFeedback(`${pending.length} record${pending.length === 1 ? '' : 's'} saved to the database and sent for review.`); } catch (cause) { setFeedback(`${cause instanceof Error ? cause.message : 'Unable to sync queued logs.'} Your data remains safely queued.`); } finally { setIsSubmitting(false); } };
  const install = async () => { if (!installPrompt) return; await installPrompt.prompt(); setInstallPrompt(null); }; const pending = outbox.filter((item) => item.status === 'PENDING_LOCAL').length;
  const enableNotifications = async () => { if (!('Notification' in window)) { setFeedback('Notifications are not available in this browser.'); return; } const permission = await Notification.requestPermission(); setFeedback(permission === 'granted' ? 'Notifications enabled.' : 'Notifications were not enabled.'); };
  return <div className="min-h-screen bg-background pb-12"><NirmaanHeader currentTab="field-log" /><main className="max-w-4xl mx-auto px-4 sm:px-6 py-6 space-y-6">
    <section className="rounded-2xl border border-border bg-card p-4 flex flex-col sm:flex-row justify-between gap-4 shadow-sm"><div className="flex gap-3"><div className={`p-2 rounded-xl ${offline ? 'bg-amber-500/10 text-amber-600' : 'bg-emerald-500/10 text-emerald-600'}`}>{offline ? <WifiOff /> : <Wifi />}</div><div><p className="text-sm font-bold">{offline ? 'Offline capture is active' : 'Ready to save field observations'}</p><p className="text-xs text-muted-foreground">Logs save directly to the database when online. If saving fails, they remain in this browser’s outbox for retry.</p></div></div><div className="flex flex-wrap gap-2"><a href="/field-log/history" className="px-3 py-2 rounded-lg border border-border text-xs font-semibold inline-flex gap-1.5 items-center"><Clock className="w-3.5 h-3.5" /> My history</a><button type="button" onClick={() => setOffline(!offline)} className="px-3 py-2 rounded-lg border border-border text-xs font-semibold">{offline ? 'Go online' : 'Test offline mode'}</button><button type="button" onClick={enableNotifications} className="px-3 py-2 rounded-lg border border-border text-xs font-semibold inline-flex gap-1.5 items-center"><Bell className="w-3.5 h-3.5" /> Alerts</button>{installPrompt && <button type="button" onClick={install} className="px-3 py-2 rounded-lg bg-primary text-primary-foreground text-xs font-bold inline-flex gap-1.5 items-center"><Download className="w-4 h-4" /> Install app</button>}</div></section>
    {feedback && <div role="status" className="p-3 rounded-xl border border-primary/20 bg-primary/5 text-xs font-semibold flex justify-between gap-3"><span>{feedback}</span><button type="button" onClick={() => setFeedback(null)} aria-label="Dismiss message">×</button></div>}
    <section className="rounded-3xl border border-border bg-card p-6 shadow-lg space-y-6"><div className="flex justify-between border-b border-border pb-4"><div><h2 className="font-bold flex gap-2 items-center"><Radio className="w-5 h-5 text-primary" /> Field observation capture</h2><p className="text-xs text-muted-foreground mt-1">Enter an observation and save it directly to the connected workspace.</p></div><span className="text-[10px] font-mono rounded bg-muted px-2 py-1 h-fit">{DEVICE}</span></div><label className="block text-xs font-bold">Project<select value={selectedProjectId} onChange={(event) => setSelectedProjectId(event.target.value)} disabled={isLoadingProjects} className="mt-1.5 w-full p-3 rounded-xl border border-border bg-background disabled:opacity-60"><option value="">{isLoadingProjects ? 'Loading projects…' : 'Select an uploaded baseline'}</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.code} — {project.name}</option>)}</select></label>{projectsError && <p className="text-xs text-destructive">Unable to load projects: {projectsError}</p>} {!isLoadingProjects && !projects.length && <p className="text-xs text-amber-700">Upload a project baseline before field logs can be stored in the database.</p>}<div className="rounded-xl border border-border bg-muted/20 p-3 space-y-2"><p className="text-xs font-bold">Optional evidence requirements</p><label className="flex items-center gap-2 text-xs font-medium"><input type="checkbox" checked={requirePhoto} onChange={(event) => setRequirePhoto(event.target.checked)} /> Require a photo</label><label className="flex items-center gap-2 text-xs font-medium"><input type="checkbox" checked={requireGpsTag} onChange={(event) => setRequireGpsTag(event.target.checked)} /> Require GPS location <span className="text-muted-foreground">(asks for permission)</span></label></div><div className="grid grid-cols-2 gap-3"><button type="button" onClick={startPhotoCapture} disabled={isLocating} className="min-h-28 rounded-2xl border-2 border-dashed border-border hover:border-primary bg-muted/20 flex flex-col items-center justify-center gap-2 text-sm font-bold disabled:opacity-50"><Camera className="w-7 h-7 text-primary" /> {isLocating ? 'Getting GPS…' : requireGpsTag ? 'Capture GPS-tagged photo' : 'Attach photo'}</button><button type="button" onClick={toggleRecord} className={`min-h-28 rounded-2xl border flex flex-col items-center justify-center gap-2 text-sm font-bold ${recording ? 'bg-red-600 text-white border-red-600 animate-pulse' : 'bg-primary text-primary-foreground'}`}>{recording ? <MicOff className="w-7 h-7" /> : <Mic className="w-7 h-7" />}{recording ? `Stop recording · ${seconds}s` : 'Record voice note'}</button><input ref={imageInput} onChange={captureImage} className="hidden" type="file" accept="image/*" capture="environment" /></div>
    {evidence.length > 0 && <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">{evidence.map((item) => <div key={item.id} className="relative overflow-hidden rounded-xl border border-border bg-muted/20"><button type="button" onClick={() => removeEvidence(item.id)} aria-label={`Remove ${item.kind === 'image' ? 'site photo' : 'voice note'}`} className="absolute right-2 top-2 z-10 inline-flex min-h-11 min-w-11 items-center justify-center rounded-full border border-border bg-background/95 text-foreground shadow-sm hover:bg-destructive hover:text-destructive-foreground"><X className="h-4 w-4" /></button><div className="aspect-square bg-muted">{item.kind === 'image' ? <img src={item.dataUrl} alt="Captured site evidence" className="h-full w-full object-cover" /> : <div className="flex h-full flex-col items-center justify-center gap-3 p-4 text-center"><Volume2 className="h-8 w-8 text-primary" /><audio controls preload="metadata" className="w-full" src={item.dataUrl}>Your browser cannot play this voice note.</audio></div>}</div><div className="p-2 text-[10px]"><p className="font-bold truncate">{item.kind === 'image' ? 'Site photo' : `Voice note · ${item.durationSeconds ?? 0}s`}</p><p className="text-muted-foreground">{stamp(item.capturedAt)}</p>{item.geoTag && <p className="mt-1 inline-flex items-center gap-1 text-emerald-700"><MapPin className="h-3 w-3" /> GPS ±{Math.round(item.geoTag.accuracyMeters)}m</p>}</div></div>)}</div>}
    <div className="grid sm:grid-cols-2 gap-4"><label className="text-xs font-bold">Discipline<select value={discipline} onChange={(event) => setDiscipline(event.target.value)} className="mt-1.5 w-full p-3 rounded-xl border border-border bg-background">{['Piping', 'Civil', 'Electrical', 'Instrumentation'].map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs font-bold">Measured quantity<input value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} type="number" className="mt-1.5 w-full p-3 rounded-xl border border-border bg-background" /></label></div><label className="block text-xs font-bold">Observation / transcript<textarea value={note} onChange={(event) => setNote(event.target.value)} rows={3} placeholder="Describe progress, conditions, incident, or potential failure." className="mt-1.5 w-full p-3 rounded-xl border border-border bg-background text-sm font-normal" /></label><button type="button" onClick={saveLog} disabled={isLocating || isSubmitting || isTranscribing} className="w-full p-3 rounded-xl bg-primary text-primary-foreground text-sm font-bold inline-flex justify-center items-center gap-2 disabled:opacity-50"><Send className="w-4 h-4" /> {isSubmitting ? 'Saving…' : isLocating ? 'Capturing location…' : 'Save log to database'}</button></section>
    <section className="rounded-3xl border border-border bg-card p-6 space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-bold text-sm">Local outbox · retry queue</h3><p className="text-xs text-muted-foreground">Only unsent records remain here. Successful saves appear in My history.</p></div><button type="button" onClick={sync} disabled={!pending || isSubmitting} className="px-4 py-2 rounded-lg bg-primary text-primary-foreground text-xs font-bold disabled:opacity-50 inline-flex gap-2 items-center"><RefreshCw className="w-3.5 h-3.5" /> Sync {pending || ''}</button></div><div className="divide-y divide-border">{outbox.length ? [...outbox].sort((a, b) => new Date(b.eventTimestampHw).getTime() - new Date(a.eventTimestampHw).getTime()).map((item) => <div key={item.clientEventId} className="py-3 flex gap-3"><div className="pt-0.5">{item.status === 'SYNCED' ? <CheckCircle2 className="w-4 h-4 text-emerald-600" /> : <Clock className="w-4 h-4 text-amber-600" />}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold">{item.rawText}</p><p className="text-[11px] text-muted-foreground mt-1">{stamp(item.eventTimestampHw)} · Seq #{item.monotonicSeq} · {item.evidence.length} attachment{item.evidence.length === 1 ? '' : 's'}</p></div><span className="text-[10px] font-bold">{item.status === 'SYNCED' ? 'SAVED' : 'QUEUED'}</span></div>) : <p className="py-6 text-center text-xs text-muted-foreground">Saved logs and unsent offline records will appear here.</p>}</div></section>
  </main></div>;
}
