import React, { useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, Database, Search, TrendingUp } from 'lucide-react';
import { NirmaanHeader } from '../components/NirmaanHeader';
import { useHistoricalBenchmarks } from '../operationsClient';

export function KnowledgeBasePage() {
  const [disciplineFilter, setDisciplineFilter] = useState('ALL');
  const [searchTerm, setSearchTerm] = useState('');
  const { benchmarks } = useHistoricalBenchmarks();
  const filteredBenchmarks = useMemo(() => benchmarks.filter((benchmark) => {
    const matchesDiscipline = disciplineFilter === 'ALL' || benchmark.discipline === disciplineFilter;
    const query = searchTerm.trim().toLowerCase();
    const matchesSearch = !query || benchmark.historicalProjectCode.toLowerCase().includes(query) || benchmark.workType.toLowerCase().includes(query) || benchmark.recordedDelays.some((delay) => delay.cause.toLowerCase().includes(query));
    return matchesDiscipline && matchesSearch;
  }), [benchmarks, disciplineFilter, searchTerm]);
  const analytics = useMemo(() => {
    const averageVariance = benchmarks.length ? benchmarks.reduce((sum, item) => sum + item.variancePercentage, 0) / benchmarks.length : 0;
    const causes = new Map<string, number>();
    benchmarks.flatMap((item) => item.recordedDelays).forEach((delay) => causes.set(delay.cause, (causes.get(delay.cause) || 0) + delay.days));
    const rankedCauses = [...causes.entries()].sort((a, b) => b[1] - a[1]);
    const totalDays = rankedCauses.reduce((sum, [, days]) => sum + days, 0);
    return { averageVariance, rankedCauses, totalDays };
  }, [benchmarks]);

  return <div className="min-h-screen bg-background pb-12"><NirmaanHeader currentTab="knowledge-base" /><main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
    <div><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-bold tracking-tight text-foreground">Closed-project historical benchmarks</h2><span className="px-2.5 py-0.5 rounded-full text-xs font-bold font-mono bg-primary/10 text-primary border border-primary/20">{benchmarks.length} records</span></div><p className="text-xs text-muted-foreground mt-1">Records appear here only after they have been added to the connected workspace database.</p></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4"><MetricCard label="Benchmark records" value={String(benchmarks.length)} copy="Closed-project duration records available in this workspace." icon={<Database className="w-4 h-4" />} /><MetricCard label="Average schedule variance" value={(analytics.averageVariance >= 0 ? '+' : '') + analytics.averageVariance.toFixed(1) + '%'} copy={benchmarks.length ? 'Calculated from the records shown below.' : 'Add records to calculate this measure.'} icon={<TrendingUp className="w-4 h-4" />} /><MetricCard label="Leading recorded delay" value={analytics.rankedCauses[0]?.[0] || 'No delay data'} copy={analytics.rankedCauses[0] ? analytics.rankedCauses[0][1] + ' recorded delay days.' : 'No historical delay causes have been recorded.'} icon={<AlertTriangle className="w-4 h-4" />} compact /></div>
    <section className="p-6 rounded-2xl border border-border bg-card/60 shadow-sm space-y-4"><div className="flex items-center justify-between gap-4"><h3 className="text-sm font-bold text-foreground flex items-center gap-2"><BarChart3 className="w-4 h-4 text-primary" />Delay causes from recorded projects</h3><span className="text-xs text-muted-foreground font-mono">{analytics.totalDays} delay days</span></div>{analytics.rankedCauses.length ? <div className="space-y-3">{analytics.rankedCauses.slice(0, 5).map(([cause, days]) => <div key={cause} className="space-y-1"><div className="flex items-center justify-between gap-3 text-xs font-semibold"><span className="text-foreground truncate">{cause}</span><span className="font-mono text-muted-foreground shrink-0">{days}d</span></div><div className="w-full bg-muted rounded-full h-2 overflow-hidden"><div className="bg-primary h-2 rounded-full" style={{ width: Math.max(3, (days / analytics.totalDays) * 100) + '%' }} /></div></div>)}</div> : <p className="py-6 text-center text-sm text-muted-foreground">No historical delay data has been added yet.</p>}</section>
    <section className="flex flex-col sm:flex-row items-center justify-between gap-4 p-4 rounded-xl border border-border bg-card/40"><div className="relative w-full sm:w-80"><Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input type="search" aria-label="Search historical benchmark records" placeholder="Search projects, work types, or delay causes…" value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} className="w-full pl-9 pr-4 py-2 text-sm rounded-lg border border-border bg-background focus:outline-none focus:ring-2 focus:ring-primary/40" /></div><div className="flex items-center gap-2 overflow-x-auto w-full sm:w-auto"><span className="text-xs text-muted-foreground whitespace-nowrap">Discipline:</span>{['ALL', 'Piping', 'Civil', 'Electrical', 'Instrumentation'].map((discipline) => <button key={discipline} onClick={() => setDisciplineFilter(discipline)} className={'px-3 py-1.5 rounded-lg text-xs font-medium transition-all ' + (disciplineFilter === discipline ? 'bg-primary text-primary-foreground font-semibold shadow-xs' : 'bg-muted text-muted-foreground hover:text-foreground')}>{discipline === 'ALL' ? 'All' : discipline}</button>)}</div></section>
    {filteredBenchmarks.length ? <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{filteredBenchmarks.map((benchmark) => <article key={benchmark.id} className="p-5 rounded-2xl border border-border bg-card shadow-sm space-y-4"><div className="flex items-center justify-between gap-3"><span className="font-mono text-xs font-bold text-primary">{benchmark.historicalProjectCode}</span><span className="px-2 py-0.5 rounded text-[10px] font-semibold bg-secondary text-secondary-foreground">{benchmark.discipline}</span></div><h4 className="text-sm font-bold text-foreground">{benchmark.workType}</h4><div className="grid grid-cols-2 gap-2 text-xs font-mono bg-muted/40 p-3 rounded-xl border border-border/60"><div><span className="text-[10px] text-muted-foreground block">Planned</span><span className="font-bold text-foreground">{benchmark.plannedDurationDays} days</span></div><div><span className="text-[10px] text-muted-foreground block">Actual</span><span className="font-bold text-foreground">{benchmark.actualDurationDays} days</span></div></div><div className="flex justify-between text-xs"><span className="text-muted-foreground">Variance</span><span className="font-mono font-bold">{benchmark.variancePercentage >= 0 ? '+' : ''}{benchmark.variancePercentage}%</span></div><div className="border-t border-border/60 pt-3 space-y-1"><span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wide">Recorded delay causes</span>{benchmark.recordedDelays.length ? benchmark.recordedDelays.map((delay, index) => <p key={index} className="text-xs text-muted-foreground flex justify-between gap-2"><span>{delay.cause}</span><span className="font-mono shrink-0">{delay.days}d</span></p>) : <p className="text-xs text-muted-foreground">No delay causes recorded.</p>}</div></article>)}</div> : <div className="rounded-2xl border border-dashed border-border bg-card/40 py-16 text-center"><h3 className="font-semibold text-foreground">No benchmark records found</h3><p className="mt-2 text-sm text-muted-foreground">Adjust your filters or add a closed-project record to the database.</p></div>}
  </main></div>;
}

function MetricCard({ label, value, copy, icon, compact = false }: { label: string; value: string; copy: string; icon: React.ReactNode; compact?: boolean }) {
  return <div className="p-5 rounded-2xl border border-border bg-card/60 shadow-sm space-y-2"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">{label}</span><div className="p-2 rounded-xl bg-primary/10 text-primary">{icon}</div></div><div className={'font-extrabold text-foreground ' + (compact ? 'text-lg' : 'text-3xl')}>{value}</div><p className="text-xs text-muted-foreground">{copy}</p></div>;
}
