'use client';

import Link from 'next/link';
import { useEffect } from 'react';
import { ArrowRight, HardHat } from 'lucide-react';

const workflows = [
  ['Field record', 'Capture a typed observation, photograph, or voice note where the work happens.', 'record'],
  ['Schedule link', 'Compare site evidence with the planned activity before it changes the programme.', 'link'],
  ['Planner review', 'Keep low-confidence matches visible for the person accountable for the schedule.', 'review'],
] as const;

const trail = [
  ['Capture', 'Preserve what was observed, when it was observed, and what supports it.'],
  ['Reconcile', 'Make the proposed activity link visible before it is accepted.'],
  ['Review', 'Give the planner a clear decision, not an unexplained update.'],
  ['Learn', 'Keep verified outcomes available as historical context.'],
];

export function LandingPage() {
  useEffect(() => {
    const sections = Array.from(document.querySelectorAll<HTMLElement>('.landing-scroll > section'));
    const observer = new IntersectionObserver(
      (entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }),
      { threshold: 0.12, rootMargin: '0px 0px -7% 0px' },
    );
    sections.forEach((section) => observer.observe(section));
    return () => observer.disconnect();
  }, []);

  return <div className="min-h-screen overflow-x-clip bg-[#fbfbfa] font-[Arial,Helvetica,sans-serif] text-[#171717] selection:bg-[#ffd52e]">
    <header className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 sm:px-8">
      <Link href="/" className="text-[25px] font-medium leading-[.82] tracking-[-.09em] sm:text-[34px]" aria-label="Nirmaan Setu home">NIRMAAN<br />SETU.</Link>
      <nav aria-label="Landing page navigation" className="hidden grid-cols-3 gap-1 rounded-full border border-black/10 bg-[#fbfbfa] p-1 text-center text-[10px] font-bold uppercase leading-[1.05] tracking-[.06em] text-[#242424] sm:grid"><a href="#evidence" className="rounded-full px-3 py-2 transition hover:bg-[#ffd52e]">Field record</a><a href="#controls" className="rounded-full px-3 py-2 transition hover:bg-[#ffd52e]">Schedule control</a><a href="#workflow" className="rounded-full px-3 py-2 transition hover:bg-[#ffd52e]">Planner review</a></nav>
      <Link href="/projects" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-black px-4 text-xs font-bold text-white transition hover:bg-[#343434] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1f39d2]">Open workspace <ArrowRight className="h-3.5 w-3.5" /></Link>
    </header>

    <main className="landing-scroll">
      <section className="border-y border-black bg-white"><TriangularMosaic className="hero-mosaic h-[155px] sm:h-[220px] lg:h-[290px]" density={496} /><div className="mx-auto max-w-[1120px] px-5 pb-18 pt-14 sm:px-8 sm:pb-28 sm:pt-20"><h1 className="max-w-[720px] text-[clamp(2.5rem,6vw,6.25rem)] font-medium leading-[.88] tracking-[-.085em]">Field work,<br />accounted for.</h1><p className="mt-8 max-w-[520px] text-[18px] leading-[1.06] tracking-[-.045em] sm:text-[25px]">Nirmaan Setu carries site observations into the project plan without hiding the evidence, the uncertainty, or the decision.</p><Link href="/field-log" className="mt-8 inline-flex min-h-11 items-center rounded-full bg-[#1f39d2] px-5 text-sm font-bold text-white transition hover:bg-[#172da5]">Record field progress</Link></div></section>

      <section className="mx-auto max-w-[1120px] px-5 py-20 sm:px-8 sm:py-28"><p className="max-w-[680px] text-[20px] leading-[.98] tracking-[-.045em] sm:text-[29px]">Project controls work when the people at the site and the people managing the plan are working from the same record.</p><div className="mt-12 grid gap-4 md:grid-cols-3">{workflows.map(([title, copy, type]) => <WorkflowCard key={title} title={title} copy={copy} type={type} />)}</div></section>

      <section id="workflow" className="mx-auto grid max-w-[1120px] gap-12 border-t border-black px-5 py-20 sm:px-8 sm:py-28 md:grid-cols-[.85fr_1.15fr]"><h2 className="max-w-[350px] text-[clamp(2rem,4vw,4rem)] font-medium leading-[.9] tracking-[-.075em]">A field record is not a status update.</h2><div className="max-w-[550px] text-[14px] leading-[1.25] tracking-[-.025em] sm:text-[17px]"><p>It is a specific observation connected to a location, a time, a discipline, and evidence. Nirmaan Setu keeps that context intact as the observation moves toward a schedule decision.</p><p className="mt-8">Upload a Primavera P6 XER or MS Project XML baseline, capture the progress from site, and inspect the proposed relationship before any verified actual changes the critical path.</p><Link href="/projects" className="mt-9 inline-flex min-h-11 items-center gap-2 rounded-full bg-black px-5 text-sm font-bold text-white transition hover:bg-[#343434]">View project controls <ArrowRight className="h-4 w-4" /></Link></div></section>

      <section className="mx-auto grid max-w-[1120px] gap-12 border-t border-black px-5 py-20 sm:px-8 sm:py-28 md:grid-cols-[.85fr_1.15fr]"><h2 className="max-w-[390px] text-[clamp(2rem,4vw,4rem)] font-medium leading-[.9] tracking-[-.075em]">Automation helps until a planner needs to explain the change.</h2><div><p className="max-w-[550px] text-sm leading-[1.3] sm:text-base">Matching can suggest the scheduled activity that best fits an observation. It should not make an invisible decision. Nirmaan Setu surfaces the match confidence and preserves the alternatives for review.</p><div className="mt-10 grid grid-cols-2 gap-6 border-y border-black py-6 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center border-2 border-dashed border-[#1f39d2] text-xl font-bold text-[#1f39d2]">?</div><p className="mt-3 text-[10px] font-bold uppercase tracking-[.14em]">Uncertain match</p><p className="mt-1 text-[11px] leading-[1.25] text-[#555]">Route it to the reviewer queue.</p></div><div><div className="mx-auto grid h-14 w-14 place-items-center border-2 border-[#171717] text-xl font-bold">✓</div><p className="mt-3 text-[10px] font-bold uppercase tracking-[.14em]">Verified actual</p><p className="mt-1 text-[11px] leading-[1.25] text-[#555]">Use it to recalculate the plan.</p></div></div></div></section>

      <section id="controls" className="border-y border-black bg-[#1f39d2] text-white"><div className="mx-auto grid max-w-[1120px] gap-12 px-5 py-20 sm:px-8 sm:py-28 md:grid-cols-[.9fr_1.1fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#ffd52e]">What stays with the record</p><h2 className="mt-6 max-w-[460px] text-[clamp(2.2rem,5vw,5.2rem)] font-medium leading-[.87] tracking-[-.085em]">Evidence first. Forecast second.</h2></div><div className="self-end text-[14px] leading-[1.25] text-white/90 sm:text-[17px]"><p>Voice notes, photographs, and written observations remain with the field event. The proposed schedule link is visible, and uncertain matches remain in the reviewer queue.</p><p className="mt-7">That gives a planner enough context to approve, reassign, or dismiss the link before the schedule is recalculated.</p></div></div><SignalDiagram /></section>

      <section id="evidence" className="mx-auto max-w-[1120px] px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-10 md:grid-cols-[.9fr_1.1fr]"><div><h2 className="text-[clamp(2rem,4vw,4rem)] font-medium leading-[.9] tracking-[-.075em]">The decision trail stays visible.</h2><p className="mt-5 max-w-[360px] text-sm leading-[1.25]">A programme is easier to trust when its updates can be traced back to the work that prompted them.</p></div><div className="self-end text-sm leading-[1.25] sm:text-base">The workflow is intentionally explicit: a baseline is ingested, an observation is captured, a candidate activity is reviewed, and verified progress becomes context for the next decision.</div></div><div className="mt-12 border-y border-black py-8"><TriangularMosaic className="h-28" density={155} compact /></div><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{trail.map(([label, copy], index) => <div key={label} className="border-t border-black pt-3"><span className="text-[10px] font-bold">0{index + 1}</span><h3 className="mt-5 text-sm font-bold">{label}</h3><p className="mt-2 text-[11px] leading-[1.3] text-[#555]">{copy}</p></div>)}</div></section>

      <section className="border-y border-black bg-[#ffd52e]"><div className="mx-auto grid max-w-[1120px] gap-10 px-5 py-20 sm:px-8 sm:py-28 md:grid-cols-[.85fr_1.15fr]"><h2 className="text-[clamp(2rem,4vw,4rem)] font-medium leading-[.9] tracking-[-.075em]">Keep the work moving, not the uncertainty.</h2><div className="text-sm leading-[1.3] sm:text-base"><p>Site teams should be able to record progress without learning a scheduling system. Planners should be able to understand how the record maps to their plan without chasing information across messages and spreadsheets.</p><p className="mt-8">Nirmaan Setu gives each role the part of the workflow it needs, while keeping one operational record underneath.</p><Link href="/reviewer-queue" className="mt-8 inline-flex min-h-11 items-center rounded-full bg-black px-5 text-sm font-bold text-white transition hover:bg-[#343434]">Open reviewer queue</Link></div></div></section>

      <section className="mx-auto max-w-[1120px] px-5 py-20 sm:px-8 sm:py-28"><h2 className="max-w-[500px] text-[clamp(2rem,4vw,4rem)] font-medium leading-[.9] tracking-[-.075em]">One workspace, built around the actual work.</h2><div className="mt-12 grid gap-4 md:grid-cols-3"><ToolTile title="Baseline intake" copy="Bring the current schedule into the workspace from P6 XER or MS Project XML." kind="baseline" /><ToolTile title="Field logger" copy="Capture text, image, and voice evidence directly from site." kind="field" /><ToolTile title="Historical context" copy="Use verified outcomes to inform the next plan and review." kind="history" /></div></section>

      <section className="border-y border-black bg-white"><div className="mx-auto grid max-w-[1120px] gap-12 px-5 py-20 sm:px-8 sm:py-28 md:grid-cols-[.85fr_1.15fr]"><h2 className="text-[clamp(2rem,4vw,4rem)] font-medium leading-[.9] tracking-[-.075em]">The record travels with the work.</h2><div className="text-sm leading-[1.3] sm:text-base"><p>Baseline uploads, site observations, reviewer decisions, and verified outcomes form one continuous operational record. Each part is useful on its own. Together they make schedule conversations more concrete.</p><p className="mt-8">The same record supports the person capturing work in the field, the planner reviewing risk, and the project team understanding the effect on the current plan.</p></div></div><div className="mx-auto grid max-w-[1120px] gap-px border-t border-black bg-black sm:grid-cols-3"><div className="bg-[#f04e2b] p-7 text-white"><p className="text-[10px] font-bold uppercase tracking-[.14em]">At site</p><p className="mt-16 text-2xl font-medium leading-[.9] tracking-[-.06em]">Record what happened.</p></div><div className="bg-[#1f39d2] p-7 text-white"><p className="text-[10px] font-bold uppercase tracking-[.14em]">In review</p><p className="mt-16 text-2xl font-medium leading-[.9] tracking-[-.06em]">See what it could change.</p></div><div className="bg-[#ffd52e] p-7 text-black"><p className="text-[10px] font-bold uppercase tracking-[.14em]">In the plan</p><p className="mt-16 text-2xl font-medium leading-[.9] tracking-[-.06em]">Keep the decision accountable.</p></div></div></section>

      <section className="bg-black px-5 py-24 text-white sm:px-8 sm:py-32"><div className="mx-auto max-w-[620px] text-center"><HardHat className="mx-auto h-6 w-6 text-[#ffd52e]" /><h2 className="mt-7 text-[clamp(2.4rem,6vw,5.5rem)] font-medium leading-[.87] tracking-[-.09em]">Bring site progress back into the plan.</h2><p className="mx-auto mt-6 max-w-[440px] text-sm leading-[1.35] text-white/70">Start in the workspace, load a project baseline, and make the next field record accountable.</p><Link href="/projects" className="mt-9 inline-flex min-h-11 items-center rounded-full bg-white px-5 text-sm font-bold text-black transition hover:bg-[#ffd52e]">Open Nirmaan Setu</Link></div></section>
    </main>
    <footer className="border-t border-black bg-white"><TriangularMosaic className="h-20" density={95} compact /><div className="mx-auto flex max-w-[1440px] flex-col gap-4 px-5 py-7 text-[11px] font-bold sm:flex-row sm:items-end sm:justify-between sm:px-8"><span>NIRMAAN SETU<br />FIELD TO PLAN</span><span>SIH26122 · OIL INDIA LIMITED<br />PROJECT CONTROLS WORKSPACE</span></div></footer>
  </div>;
}

function TriangularMosaic({ className, density, compact = false }: { className: string; density: number; compact?: boolean }) {
  const columns = compact ? 26 : 62; const rows = Math.ceil(density / columns); const cell = 1000 / columns;
  const triangles = Array.from({ length: Math.min(density, columns * rows) }, (_, index) => { const column = index % columns; const row = Math.floor(index / columns); const ordered = row < rows * .44; const turn = ordered ? (column + row) % 4 : (index * 7 + row * 3) % 4; const tones = ['#1f39d2', '#ffd52e', '#171717', '#f04e2b']; return { x: column * cell, y: row * cell, turn, color: tones[(column * 3 + row) % tones.length], muted: ordered ? .78 : .3 + ((index % 7) / 10) }; });
  const isHero = className.includes('hero-mosaic');
  return <div className={`relative overflow-hidden bg-white ${className}`} aria-hidden="true"><svg viewBox={`0 0 1000 ${rows * cell}`} preserveAspectRatio="none" className="h-full w-full">{triangles.map((triangle, index) => { const s = cell; const points = triangle.turn === 0 ? `${triangle.x},${triangle.y} ${triangle.x + s},${triangle.y} ${triangle.x},${triangle.y + s}` : triangle.turn === 1 ? `${triangle.x + s},${triangle.y} ${triangle.x + s},${triangle.y + s} ${triangle.x},${triangle.y}` : triangle.turn === 2 ? `${triangle.x + s},${triangle.y + s} ${triangle.x},${triangle.y + s} ${triangle.x + s},${triangle.y}` : `${triangle.x},${triangle.y + s} ${triangle.x},${triangle.y} ${triangle.x + s},${triangle.y + s}`; return <g key={index} className={isHero ? 'hero-mosaic-piece' : undefined} style={isHero ? { animationDelay: `${-(index % 12) * 0.55}s`, animationDuration: `${6 + (index % 5)}s` } : undefined}><polygon points={points} fill={triangle.color} opacity={triangle.muted} /></g>; })}</svg></div>;
}

function WorkflowCard({ title, copy, type }: { title: string; copy: string; type: string }) {
  const images = { record: ['/field-reference-open-pit.png', 'Open-pit field work'], link: ['/field-reference-processing.png', 'Processing operations'], review: ['/field-reference-4.png', 'Underground field review'] } as const;
  const [src, alt] = images[type as keyof typeof images] || images.record;
  return <article><div className="relative aspect-[1.25] overflow-hidden bg-[#efefec]"><img src={src} alt={alt} className="h-full w-full object-cover transition-transform duration-700 hover:scale-105" /></div><h3 className="mt-4 text-sm font-bold tracking-[-.04em]">{title}</h3><p className="mt-1 max-w-[270px] text-[11px] leading-[1.25] text-[#555]">{copy}</p></article>;
}

function SignalDiagram() { const dots = Array.from({ length: 160 }, (_, index) => ({ x: 20 + index * 6, y: 75 + Math.sin(index / 10) * 35 + ((index * 17) % 29), color: index % 9 === 0 ? '#ffd52e' : '#fff' })); return <div className="mx-auto max-w-[1120px] px-5 pb-16 sm:px-8 sm:pb-24"><svg viewBox="0 0 1000 210" className="record-flow h-auto w-full" aria-hidden="true"><path d="M40 135 C200 30 300 180 470 120 S720 50 960 135" fill="none" stroke="#ffffff" strokeOpacity=".35" strokeWidth="1" />{dots.map((dot, index) => <circle key={index} cx={dot.x} cy={dot.y} r={index % 10 === 0 ? 3 : 1.8} fill={dot.color} />)}</svg></div>; }


function ToolTile({ title, copy, kind }: { title: string; copy: string; kind: 'baseline' | 'field' | 'history' }) { const images = { baseline: ['/field-reference-processing.png', 'Processing plant baseline'], field: ['/field-reference-4.png', 'Underground field work'], history: ['/field-reference-sustainable.png', 'Sustainable mine operations'] } as const; const [src, alt] = images[kind]; return <article className="border border-black bg-white"><div className="relative aspect-[1.24] overflow-hidden bg-[#eee]"><img src={src} alt={alt} className="h-full w-full object-cover transition-transform duration-700 hover:scale-105" /></div><div className="p-4"><h3 className="text-sm font-bold tracking-[-.04em]">{title}</h3><p className="mt-2 text-[11px] leading-[1.3] text-[#555]">{copy}</p></div></article>; }
