import Link from "next/link";

const constructionImage = "https://images.unsplash.com/photo-1632201147654-f6f54427e538?auto=format&fit=crop&fm=jpg&q=85&w=1800";
const crewImage = "https://images.unsplash.com/photo-1747056711958-9d8c3b97b578?auto=format&fit=crop&fm=jpg&q=85&w=1400";

const steps = [
  ["01", "Capture from the field", "Turn site notes, photos, quantities and delays into structured updates—online or offline."],
  ["02", "See the schedule move", "Link every field event to its activity, dependency and milestone in the CPM plan."],
  ["03", "Act before it slips", "Give project leaders an auditable view of risk, progress and the next best action."],
];

const outcomes = [
  "Field notes that reach the planning team the same day",
  "Photo-backed evidence for every critical update",
  "Early warnings when milestone dependencies are at risk",
];

export function LandingPage() {
  return (
    <div className="min-h-screen overflow-hidden bg-[#f8f4d9] text-[#1b2119] selection:bg-[#d8eba8] selection:text-[#1b2119]">
      <main className="mx-auto max-w-[1440px] px-4 pb-5 pt-4 sm:px-6 lg:px-10">
        <nav className="flex items-center justify-between rounded-full border border-[#1b2119]/15 bg-[#fffdeb]/80 px-4 py-3 backdrop-blur sm:px-6">
          <Link href="/" className="flex items-center gap-2 font-semibold tracking-[-0.04em]"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#0c493c] font-serif text-lg text-[#f8f4d9]">N</span><span>Nirmaan Setu</span></Link>
          <div className="hidden items-center gap-6 text-sm text-[#4f574a] md:flex"><a href="#how-it-works" className="transition hover:text-[#0c493c]">How it works</a><a href="#outcomes" className="transition hover:text-[#0c493c]">Outcomes</a><a href="#field-ready" className="transition hover:text-[#0c493c]">Field-ready</a></div>
          <Link href="/login" className="rounded-full bg-[#0c493c] px-4 py-2 text-sm font-medium text-[#f8f4d9] transition hover:bg-[#153a30]">Sign in</Link>
        </nav>

        <section className="px-2 pb-12 pt-16 text-center sm:px-8 sm:pt-24">
          <p className="mb-5 text-xs font-bold uppercase tracking-[0.2em] text-[#246d57]">Built for capital projects</p>
          <h1 className="mx-auto max-w-5xl font-serif text-5xl leading-[0.94] tracking-[-0.065em] text-[#22251e] sm:text-7xl lg:text-[6.8rem]">Keep every site decision <em className="font-normal text-[#1e765c]">on schedule.</em></h1>
          <p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-[#505747] sm:text-lg">Nirmaan Setu connects field intelligence to dynamic CPM schedules, so Oil India project teams can move from daily observations to confident action.</p>
          <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/signup" className="rounded-full bg-[#0c493c] px-6 py-3 text-sm font-semibold text-[#f8f4d9] transition hover:-translate-y-0.5 hover:bg-[#153a30]">Start a project workspace</Link><a href="#how-it-works" className="rounded-full border border-[#1b2119]/30 bg-transparent px-6 py-3 text-sm font-semibold transition hover:bg-[#fffdeb]">Explore the workflow</a></div>
        </section>

        <section className="relative overflow-hidden rounded-[2rem] bg-[#111612] px-5 pb-0 pt-7 text-[#f9f5d9] sm:px-10 sm:pt-10 lg:min-h-[570px]">
          <div className="relative z-10 max-w-xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#b9d69c]">One shared project pulse</p><h2 className="mt-4 font-serif text-4xl leading-none tracking-[-0.045em] sm:text-6xl">From field signal to schedule certainty.</h2><p className="mt-5 max-w-md text-sm leading-6 text-[#d1d6bd] sm:text-base">A calm, connected command layer for the reality of live construction: work fronts, evidence, approvals and dependencies.</p></div>
          <div className="relative z-10 mt-8 grid max-w-xl grid-cols-3 gap-2 rounded-2xl border border-white/10 bg-white/5 p-3 backdrop-blur sm:absolute sm:right-8 sm:top-12 sm:mt-0 sm:w-[430px]">{[["Work fronts", "18 active"], ["Evidence", "42 new"], ["Schedule", "On track"]].map(([label, value]) => <div key={label} className="rounded-xl bg-[#f8f4d9] p-3 text-[#182119]"><p className="text-[10px] uppercase tracking-wider text-[#5e695a]">{label}</p><p className="mt-4 font-serif text-lg leading-none">{value}</p></div>)}</div>
          <div className="relative mt-7 h-64 overflow-hidden rounded-t-[1.5rem] sm:absolute sm:bottom-0 sm:left-8 sm:right-8 sm:mt-0 sm:h-[290px]"><img src={constructionImage} alt="Construction crew at an active building site" className="h-full w-full object-cover object-center opacity-75" /><div className="absolute inset-0 bg-gradient-to-t from-[#111612] via-transparent to-transparent" /><div className="absolute bottom-5 left-5 rounded-2xl border border-white/15 bg-[#111612]/85 px-4 py-3 backdrop-blur"><p className="text-xs text-[#b9d69c]">Today&apos;s progress</p><p className="mt-1 font-serif text-xl">Foundation package · 78%</p></div></div>
        </section>

        <section id="outcomes" className="grid gap-8 px-2 py-20 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-end lg:py-28"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#246d57]">Built around the work</p><h2 className="mt-4 max-w-md font-serif text-5xl leading-[0.98] tracking-[-0.055em] sm:text-6xl">Clarity that keeps work moving.</h2></div><div className="space-y-4 border-t border-[#1b2119]/20 pt-5">{outcomes.map((outcome, index) => <div key={outcome} className="flex gap-5"><span className="font-serif text-2xl text-[#b85b2b]">0{index + 1}</span><p className="pt-1 text-lg leading-7 text-[#424a3e]">{outcome}</p></div>)}</div></section>

        <section id="how-it-works" className="rounded-[2rem] bg-[#d9c1ef] px-5 py-10 sm:px-10 sm:py-14"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#5f3d77]">A connected workflow</p><h2 className="mt-4 font-serif text-4xl leading-none tracking-[-0.05em] sm:text-6xl">The work is complex. Your next step shouldn&apos;t be.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{steps.map(([number, title, copy]) => <article key={number} className="rounded-2xl bg-[#fffdeb]/75 p-6"><span className="font-serif text-2xl text-[#7e438b]">{number}</span><h3 className="mt-10 font-serif text-2xl tracking-[-0.035em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#4a4e44]">{copy}</p></article>)}</div></section>

        <section id="field-ready" className="grid gap-8 px-2 py-20 sm:px-8 lg:grid-cols-2 lg:py-28"><div className="relative min-h-[410px] overflow-hidden rounded-[2rem] bg-[#274f42]"><img src={crewImage} alt="Workers coordinating at a construction site" className="absolute inset-0 h-full w-full object-cover opacity-70" /><div className="absolute inset-0 bg-gradient-to-t from-[#10271f] via-[#10271f]/10 to-transparent" /><div className="absolute bottom-0 p-7 text-[#f8f4d9]"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#c6e3a9]">Made for the field</p><p className="mt-3 max-w-sm font-serif text-3xl leading-none tracking-[-0.04em]">Evidence stays connected to the work, even when the network does not.</p></div></div><div className="flex flex-col justify-center lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#246d57]">For every role on site</p><h2 className="mt-4 font-serif text-5xl leading-[0.95] tracking-[-0.055em] sm:text-6xl">A better handoff starts here.</h2><p className="mt-6 max-w-md text-base leading-7 text-[#505747]">Supervisors record what happened. Engineers understand its impact. Project leaders get the decision trail they need—without chasing spreadsheets.</p><div className="mt-8 flex flex-wrap gap-2">{["Offline field capture", "Photo & document evidence", "CPM activity linking", "Role-based views"].map((item) => <span key={item} className="rounded-full border border-[#1b2119]/20 px-3 py-2 text-xs font-medium">{item}</span>)}</div></div></section>

        <section className="rounded-[2rem] bg-[#111612] px-6 py-12 text-center text-[#f8f4d9] sm:px-10 sm:py-16"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#b9d69c]">Bring the site closer</p><h2 className="mx-auto mt-4 max-w-3xl font-serif text-5xl leading-[0.94] tracking-[-0.06em] sm:text-7xl">Build with the whole picture in view.</h2><p className="mx-auto mt-6 max-w-xl text-sm leading-6 text-[#d1d6bd]">Nirmaan Setu turns field data into project confidence—from first observation to final handover.</p><Link href="/signup" className="mt-8 inline-block rounded-full bg-[#d8eba8] px-6 py-3 text-sm font-semibold text-[#18342b] transition hover:bg-[#ebf7c7]">Create your workspace</Link></section>

        <section className="px-2 py-20 sm:px-8 lg:py-28">
          <div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#246d57]">A live project rhythm</p><h2 className="mt-4 font-serif text-5xl leading-[0.95] tracking-[-0.055em] sm:text-6xl">Less chasing. More certainty.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-[#505747]">Nirmaan Setu creates a clear path from a site observation to a decision the whole project can trust.</p></div>
          <div className="mt-12 overflow-hidden rounded-[2rem] border border-[#1b2119]/15 bg-[#fffdeb] p-4 sm:p-7"><div className="grid gap-4 md:grid-cols-[0.9fr_1.1fr]"><div className="rounded-2xl bg-[#e4eed0] p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#42664b]">Site update · 10:42 AM</p><p className="mt-8 font-serif text-3xl leading-none tracking-[-0.04em]">Concrete pour paused at chainage 4+200.</p><div className="mt-8 flex items-center gap-3 rounded-xl border border-[#1b2119]/10 bg-[#fffdeb]/70 p-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#d6854c] text-xs font-bold text-white">RK</span><div><p className="text-sm font-semibold">R. Kumar</p><p className="text-xs text-[#5c6758]">Field engineer · evidence attached</p></div></div></div><div className="rounded-2xl bg-[#143f35] p-6 text-[#f8f4d9]"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#b9d69c]">Schedule impact · assessed</p><div className="mt-7 space-y-3"><div className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-center justify-between text-sm"><span>Foundation package</span><span className="text-[#d8eba8]">78% complete</span></div><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-2 w-[78%] rounded-full bg-[#d8eba8]" /></div></div><div className="rounded-xl border border-[#e0a06e]/30 bg-[#e0a06e]/10 p-4"><p className="text-sm font-semibold text-[#ffd6b4]">Milestone risk identified</p><p className="mt-1 text-xs leading-5 text-[#d1d6bd]">Review the temporary material approval before tomorrow&apos;s workfront opens.</p></div></div></div></div></div>
        </section>

        <section className="rounded-[2rem] bg-[#e8e6d3] px-5 py-12 sm:px-10 sm:py-16"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#527052]">Built around real work</p><h2 className="mt-4 font-serif text-5xl leading-[0.95] tracking-[-0.055em] sm:text-6xl">One system. Every project conversation.</h2></div><div className="grid gap-x-10 gap-y-9 sm:grid-cols-2"><article><p className="font-serif text-3xl text-[#b85b2b]">01</p><h3 className="mt-3 font-serif text-2xl">Daily field logs</h3><p className="mt-2 text-sm leading-6 text-[#505747]">Capture progress, blockers and observations where work actually happens.</p></article><article><p className="font-serif text-3xl text-[#b85b2b]">02</p><h3 className="mt-3 font-serif text-2xl">Evidence you can trace</h3><p className="mt-2 text-sm leading-6 text-[#505747]">Connect photos, files and notes to a package, activity and accountable owner.</p></article><article><p className="font-serif text-3xl text-[#b85b2b]">03</p><h3 className="mt-3 font-serif text-2xl">Risk before rework</h3><p className="mt-2 text-sm leading-6 text-[#505747]">Surface schedule pressure early enough to coordinate a useful response.</p></article><article><p className="font-serif text-3xl text-2xl text-[#b85b2b]">04</p><h3 className="mt-3 font-serif text-2xl">A shared decision trail</h3><p className="mt-2 text-sm leading-6 text-[#505747]">Give every stakeholder the same context, without another status meeting.</p></article></div></div></section>

        <section className="grid gap-6 px-2 py-20 sm:px-8 lg:grid-cols-[1.15fr_0.85fr] lg:py-28"><div className="rounded-[2rem] bg-[#e8ddc0] p-7 sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#795d31]">Your project data stays yours</p><h2 className="mt-4 max-w-lg font-serif text-4xl leading-[0.98] tracking-[-0.05em] sm:text-5xl">Evidence, access and accountability—designed into the workflow.</h2><p className="mt-6 max-w-lg text-sm leading-6 text-[#5b5747]">Role-aware workspaces help teams share the right project context with the right people, while keeping an auditable record of what changed and why.</p><Link href="/login" className="mt-8 inline-block rounded-full border border-[#1b2119]/25 px-5 py-3 text-sm font-semibold transition hover:bg-[#fffdeb]">See the workspace</Link></div><div className="rounded-[2rem] bg-[#0c493c] p-7 text-[#f8f4d9] sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#b9d69c]">Project-ready</p><div className="mt-10 space-y-5">{[["Offline-first", "Keep essential field capture moving when connectivity drops."], ["Role-based", "Show each team the context and actions relevant to their work."], ["Auditable", "Keep decisions connected to supporting project evidence."]].map(([title, copy]) => <div key={title} className="border-b border-white/15 pb-5 last:border-0"><p className="font-serif text-2xl">{title}</p><p className="mt-1 text-sm leading-6 text-[#d1d6bd]">{copy}</p></div>)}</div></div></section>

        <section className="overflow-hidden rounded-[2rem] bg-[#111612] px-5 py-12 text-[#f8f4d9] sm:px-10 sm:py-16"><div className="grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#b9d69c]">From the teams closest to the work</p><h2 className="mt-4 font-serif text-5xl leading-[0.95] tracking-[-0.05em]">Project confidence starts on site.</h2></div><div className="grid gap-4 md:grid-cols-2"><figure className="rounded-2xl bg-[#d9c1ef] p-6 text-[#201a25]"><blockquote className="font-serif text-2xl leading-tight">“When evidence and the activity plan sit together, our reviews begin with the decision—not a search for context.”</blockquote><figcaption className="mt-8 text-xs font-bold uppercase tracking-[0.15em] text-[#674d75]">Project controls lead · capital works</figcaption></figure><figure className="rounded-2xl border border-white/10 bg-white/5 p-6"><blockquote className="font-serif text-2xl leading-tight">“Field updates become useful the moment the planning team can see their consequence.”</blockquote><figcaption className="mt-8 text-xs font-bold uppercase tracking-[0.15em] text-[#b9d69c]">Site engineer · project delivery</figcaption></figure></div></div></section>

        <section className="px-2 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-3xl"><p className="text-center text-xs font-bold uppercase tracking-[0.2em] text-[#246d57]">Questions, answered</p><h2 className="mt-4 text-center font-serif text-5xl leading-[0.95] tracking-[-0.055em] sm:text-6xl">Good project questions.</h2><div className="mt-12 divide-y divide-[#1b2119]/20 border-y border-[#1b2119]/20">{[["Who is Nirmaan Setu for?", "For site teams, engineers, planners and project leaders who need one reliable view of live work and its schedule impact."], ["Can we use it in the field?", "Yes. The field workflow is designed for quick capture of notes, photos and progress updates where construction is happening."], ["How does it support schedule management?", "Project events are connected to activities, dependencies and milestones, making potential schedule pressure visible with its supporting evidence."], ["Can different teams have different access?", "Yes. Workspaces can be structured around roles so each person sees the project context that supports their responsibilities."]].map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-serif text-xl sm:text-2xl">{question}<span className="text-[#b85b2b] transition group-open:rotate-45">+</span></summary><p className="max-w-2xl pt-3 text-sm leading-6 text-[#505747]">{answer}</p></details>)}</div></div></section>

        <footer className="flex flex-col gap-5 px-3 pb-4 pt-10 text-xs text-[#667060] sm:flex-row sm:items-end sm:justify-between"><div><p className="font-serif text-2xl text-[#1b2119]">Nirmaan Setu</p><p className="mt-1">Project intelligence for work that matters.</p></div><p>Construction photography from <a className="underline underline-offset-2" href="https://unsplash.com" target="_blank" rel="noreferrer">Unsplash</a>.</p></footer>
      </main>
    </div>
  );
}
