import { type DailyStats, type PageViewSource } from "@prisma/client";
import { HttpError } from "../server/validation";

type DailyStatsWithSources = DailyStats & {
  sources: PageViewSource[];
};

type DailyStatsValues = {
  dailyStats: DailyStatsWithSources;
  weeklyStats: DailyStatsWithSources[];
};

export const getDailyStats = async (_args: void, context: any) => {
  if (!context.user) {
    throw new HttpError(
      401,
      "Only authenticated users are allowed to perform this operation",
    );
  }

  if (!context.user.isAdmin) {
    throw new HttpError(
      403,
      "Only admins are allowed to perform this operation",
    );
  }

  const statsQuery = {
    orderBy: {
      date: "desc",
    },
    include: {
      sources: true,
    },
  } as const;

  const [dailyStats, weeklyStats] = await context.prisma.$transaction([
    context.prisma.dailyStats.findFirst(statsQuery),
    context.prisma.dailyStats.findMany({ ...statsQuery, take: 7 }),
  ]);

  if (!dailyStats) {
    console.log(
      "\x1b[34mNote: No daily stats have been generated by the calculateDailyStatsJob yet. \x1b[0m",
    );
    return undefined;
  }

  return { dailyStats, weeklyStats };
};
